package de.dhbw.askme.domain

import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id

@Entity
/**
 * Sample domain class
 */
data class User(
    @Id
    @GeneratedValue
    /**
     * Id is generated by the database
     */
    var id: String,
    var name: String

) {
    override fun toString(): String {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}'
    }
}